from enum import Enum

class Occupation(Enum):
    OTHER = "Other"
    ACADEMIC_EDUCATOR = "Academic Educator"
    ARTIST = "Artist"
    CLERICAL_ADMIN = "Clerical Admin"
    COLLEGE_GRAD_STUDENT = "College Grad Student"
    CUSTOMER_SERVICE = "Customer Service"
    DOCTOR_HEALTH_CARE = "Doctor Health Care"
    EXECUTIVE_MANAGERIAL = "Executive Managerial"
    FARMER = "Farmer"
    HOMEMAKER = "Homemaker"
    K12_STUDENT = "K12 Student"
    LAWYER = "Lawyer"
    PROGRAMMER = "Programmer"
    RETIRED = "Retired"
    SALES_MARKETING = "Sales Marketing"
    SCIENTIST = "Scientist"
    SELF_EMPLOYED = "Self Employed"
    TECHNICIAN_ENGINEER = "Technician Engineer"
    TRADESMAN_CRAFTSMAN = "Tradesman Craftsman"
    UNEMPLOYED = "Unemployed"
    WRITER = "Writer"
